query getAllDocumentation {
  documentations {
    data {
      id
      attributes {
        section_title
        subsections {
          title
          content
          href
        }
      }
    }
  }
}
