query getAllApplications{
  appPages{
    data{
      attributes{
        tool{
          data{
            attributes{
              name
              icon{
                data{
                  attributes{
                    url
                    alternativeText
                  }
                }
              }
            }
          }
        }
        grabber
        description
        features{
          title
          description
          image{
            data{
              attributes{
                url
                alternativeText
              }
            }
          }
        }
      }
    }
  }
}