query getBlogAuthor($author: String!){
  usersPermissionsUsers(filters:{name:{eq: $author}}){
    data{
      attributes{
        name,
        displayEmail,
        company,
        jobTitle,
        description,
        photo{
          data{
            attributes{
              name,
              url,
            }
          }
        }
        linkedIn,
        twitter,
        facebook,
        instagram,
      }
    }
  }
}