query getBlogDataFromAuthor($author: String!){
  blogPosts(filters:{author:{eq: $author}}){
    data {
      id,
      attributes {
        title,
        category,
        description,
        content,
        date,
        author,
      }
    }
  }
}