query getBlogDataFromID($id: ID!){
  blogPost(id: $id){
    data {
      attributes {
        title,
        category,
        description,
        content,
        date,
        author,
      }
    }
  }
}