query getConvertFromHDFs{
  convertFromHdfs{
    data{
       attributes{
        name
        logo{
          data{
            attributes{
              name
              url
            }
          }
        }
        href
      }
    }
  }
}