query getDocumentation {
  currentDoc: documentations {
    data {
      id
      attributes {
        section_title
        subsections {
          id
          title
          href
          content
        }
      }
    }
  }

  allLinks: documentations(sort: "order_id:asc") {
    data {
      attributes {
        section_title
        subsections {
          title
          href
        }
      }
    }
  }
}
