query getFrameworkPage($page: String!){
  frameworkPages(filters:{capability:{name:{eqi: $page}}}){
    data{
      attributes{
        capability{
          data{
            attributes{
              name
              icon{
                data{
                  attributes{
                    url
                  }
                }
              }
            }
          }
        }
        grabber
        description
      }
    }
  }
}