query getGuidanceDataFromID($id: ID!) {
  guidance(id: $id) {
    data {
      id
      attributes {
        name
        type
        category
        source
        date
        version {
          __typename
          ... on ComponentVersionHistoryCis {
            version
          }
          ... on ComponentVersionHistoryStig {
            version
          }
          ... on ComponentVersionHistoryVendor {
            version
          }
          ... on ComponentVersionHistoryStigReady {
            version
          }
        }
        hardening {
          data {
            id
            attributes {
              name
              name_long
              source
              code_last_updated
              platform {
                data {
                  attributes {
                    name
                    link
                    icon {
                      data {
                        attributes {
                          name
                          url
                          alternativeText
                        }
                      }
                    }
                  }
                }
              }
              partner {
                data {
                  attributes {
                    name
                    name_long
                    link
                    icon {
                      data {
                        attributes {
                          name
                          url
                          alternativeText
                        }
                      }
                    }
                  }
                }
              }
            }
          }
        }
        validation {
          data {
            id
            attributes {
              name
              name_long
              source
              code_last_updated
              platform {
                data {
                  attributes {
                    name
                    link
                    icon {
                      data {
                        attributes {
                          name
                          url
                          alternativeText
                        }
                      }
                    }
                  }
                }
              }
              partner {
                data {
                  attributes {
                    name
                    name_long
                    link
                    icon {
                      data {
                        attributes {
                          name
                          url
                          alternativeText
                        }
                      }
                    }
                  }
                }
              }
            }
          }
        }
      }
    }
  }
}
