query getProfileData($type: String!){
	profiles(filters:{type:{eq: $type}}){
    data{
      attributes{
        type,
        category,
        name,
        name_long,
        url,
        partner {
          data{
            attributes{
              name,
            }
          }
        },
        platform{
          data{
            attributes{
              name,
            }
          }
        },
        # profile_category{
        #   data{
        #     attributes{
        #       category,
        #     }
        #   }
        # },
#         version_history{
          
#         },
      }
  	}
  }
}