query whenToUseIt{
  textContents(
    filters: {
      name: {
        in: ["Planning", "Development", "Assessment", "Operations"]
      }
    }) {
    data {
      id
      attributes {
        name
        text
      }
    }
  }
} 